---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.align = "center",
  fig.path = "man/figures/README-"
)
```
## Overview

<!-- badges: start -->
<!-- badges: end -->

User-friendly and flexible algorithm for time series **segmentation** with a Regression model with a Hidden Logistic Process (RHLP).

## Installation

You can install the development version of RHLP from [GitHub](https://github.com/) with:

```{r, eval = FALSE}
# install.packages("devtools")
devtools::install_github("fchamroukhi/RHLP")
```

To build *vignettes* for examples of usage, type the command below instead:

```{r, eval = FALSE}
# install.packages("devtools")
devtools::install_github("fchamroukhi/RHLP", 
                         build_opts = c("--no-resave-data", "--no-manual"), 
                         build_vignettes = TRUE)
```

Use the following command to display vignettes:

```{r, eval = FALSE}
browseVignettes("RHLP")
```

## Usage

```{r, message = FALSE}
library(RHLP)

data("simulatedtimeserie")
fData <- FData(simulatedtimeserie$X, t(simulatedtimeserie$Y))

K <- 5 # number of regimes (mixture components)
p <- 3 # dimension of beta (order of the polynomial regressors)
q <- 1 # dimension of w (order of the logistic regression: to be set to 1 for segmentation)
variance_type <- variance_types$hetereskedastic

modelRHLP <- ModelRHLP(fData, K, p, q, variance_type)

n_tries <- 1
max_iter = 1500
threshold <- 1e-6
verbose <- TRUE
verbose_IRLS <- FALSE

solution <- EM(modelRHLP, n_tries, max_iter, threshold, verbose, verbose_IRLS)

solution$plot()
```
